pluginManagement {
    repositories {
        def isCi = System.getenv("CI") != null
        if (!isCi) {
            maven { url "https://maven.aliyun.com/repository/google" }
            maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
        }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        def isCi = System.getenv("CI") != null
        if (!isCi) {
            maven { url "https://maven.aliyun.com/repository/google" }
            maven { url "https://maven.aliyun.com/repository/central" }
            maven { url "https://mirrors.cloud.tencent.com/nexus/repository/maven-public/" }
        }
        google()
        mavenCentral()
    }
}

rootProject.name = "NukaCast"
include(":app")
